### ISSUE TITLE
Spam to mailchimp

### ISSUE THREAD

**Issue by DavidWells** [inboundnow/cta#100]
Do API connections pass through the same spam scrutiny before the API calls are made? 

Aka do they pass through akismet before hitting mailchimp API?

http://support.inboundnow.com/support/topic/spam-to-mailchimp-list/

**Comment by atwellpub** [comment]
They were not. I switched them inside the conditional. If Akismet filtering is off they should fire normally as well.

**Comment by atwellpub** [comment]
https://github.com/inboundnow/cta/commit/569c882b8322dd00d2213dfef9b5d2fff46311b6 (fix indentation)
