### ISSUE TITLE
What are these hidden inputs used for?

### ISSUE THREAD

**Issue by DavidWells** [inboundnow/cta#114]
https://github.com/inboundnow/cta/blob/master/classes/class.metaboxes.wp-call-to-action.php#L723-L727

Reformatting customizer into a single shared class across all components.

What do those hidden inputs do on save?

**Comment by atwellpub** [comment]
Looks like the open_variation input is used with the template selector:
https://github.com/inboundnow/cta/search?utf8=%E2%9C%93&q=open_variation

The other one looks like it's used to store variation status information on a current variation.
