### ISSUE TITLE
Where did my new marketing icon go?

### ISSUE THREAD

**Issue by DavidWells** [inboundnow/cta#115]
A lot of my recent changes are gone...

http://www.screencast.com/t/CRjjPlsdkm

Where did my new icon go?

**Comment by DavidWells** [comment]
I had an entirely new icon in there for the menu + marketing button

**Comment by DavidWells** [comment]
https://github.com/inboundnow/cta/commit/fdfb8922df8d1f725af633182d082d3804018e47

**Comment by DavidWells** [comment]
Please be more careful

**Comment by atwellpub** [comment]
I did not see any changes, or notice any differences. When I removed that bit it looked like redundant code. 

To avoid further conflicts during these days of refactoring, document what you're doing as much as possible on issues. I will be more attentive, though I'm not sure what's happened.

**Comment by DavidWells** [comment]
Its cool. Just want to make sure we are on same page and my changes don't get hosed.

The git commit messages are the changes being made. This 'no message' commit is the culprit https://github.com/inboundnow/cta/commit/8343e8412382bba1fe3f65da9ce67e511e911cb6 . I'm guilty of vague commit messages too

Lets try and do stuff like http://www.laurencegellert.com/2013/07/how-to-write-a-proper-commit-message/ and http://chris.beams.io/posts/git-commit/
