### ISSUE TITLE
Make change in latest tag and trunk for WP 4.3 launch

### ISSUE THREAD

**Issue by DavidWells** [inboundnow/cta#119]
Hey hudson,

Can you make this quick SVN change in latest tag and trunk

This is the 2 line change : https://github.com/inboundnow/cta/commit/e851cec99f2070f184ed873113a17e13e7fa83a9

This gets rid of PHP warnings with wordpress 4.3

**Comment by atwellpub** [comment]
What about here too?
https://github.com/inboundnow/landing-pages/blob/1.8.8/modules/module.widgets.php#L23

**Comment by DavidWells** [comment]
I thought I got that one in master.

But yeah all $this->wp_widget needs to be the other way

**Comment by atwellpub** [comment]
kk taken care of.
