### ISSUE TITLE
New shared customizer implemented

### ISSUE THREAD

**Issue by DavidWells** [inboundnow/cta#120]
The updated customizer code is backed into the /shared folder and has been plugged in for CTA and landing pages.

Can you try them both and verify?

Also, I think its time for a release. Are things clear for a version bump for all plugins?

**Comment by atwellpub** [comment]
### Landing Pages
* [ ] Check load variation 1
* [ ] Check save variation 1
* [ ] Check load variation 2
* [ ] Check save variation 2

### Calls to Action
* [ ] Check load variation 1
* [ ] Check save variation 1
* [ ] Check load variation 2
* [ ] Check save variation 2

Landing Pages isn't ready for release until I can get ACF shipped with it for the converted countdown lander. I did not build that into a feature branch first. I'm going to convert the others in a feature branch though.

**Comment by DavidWells** [comment]
Ok I'm going to look into revamping some additional JS to a cleaner setup that will hopefully avoid minification issues

**Comment by atwellpub** [comment]
@DavidWells 

Noticing in landing page after saving within the customizer, the next variation loads in the preview screen rather than the same variation.

**Comment by atwellpub** [comment]
Also noticing that the above does not happen with CTA, but it does break after a normal non customizer save:

http://screencast.com/t/2usP6dXwE

**Comment by DavidWells** [comment]
K i will have a look

**Comment by DavidWells** [comment]
Updated. Can you pull and try again.

I couldn't reproduce the wrong variation loading on save

**Comment by atwellpub** [comment]
Have to head out for th night, havent tested cta yet, but landing pages is still rotating variations on customizer save... for me.
