### ISSUE TITLE
Async for CTA

### ISSUE THREAD

**Issue by DavidWells** [inboundnow/cta#121]
Hey hudson, 

Why is this async false again? https://github.com/inboundnow/cta/blob/38cbdf3cc73af1da864dcb884e11c320212512e5/assets/js/cta-variation.js#L107

I'm going to spend some time refactoring the CTA frontend functionality to be friendly towards the minification issues we run into from time to time

**Comment by atwellpub** [comment]
I believe it is beacuse we send data about what variations were loaded back to the server at the end of the page load. In order for this data to be correct we need to know correctly what variations were loaded. Or else we send back false data. 

So we we need to wait for all the data to come back before continuing to record impression data. 

When you begin studying for a refactor make sure that static widgets, dynamic widgets, and shortcodes are all running at the same time. 

It may be possible to record impressions on the first ajax call of the 'cta_get_variation' method. But that wont account for sites with split testing disabled and shortcodes who have their variation already defined. The final ajax call that records loaded cta impressions will still need to fire for them, 

Here is where we reveal ctas recorded in our data object/array and also set their impressions:
https://github.com/inboundnow/cta/blob/38cbdf3cc73af1da864dcb884e11c320212512e5/assets/js/cta-variation.js#L131-L151

You're welcome to test with the async set to true, I remember this work requiring a lot of concentration and care. It could be that at the time I did not understand aync very well too. I just don't know at the moment without running tests.

Trying to catch up with my other work atm.
