### ISSUE TITLE
Legacy code

### ISSUE THREAD

**Issue by DavidWells** [inboundnow/cta#123]
Doesn't look like this code runs anymore: https://github.com/inboundnow/cta/blob/8b1ac5dd5dd2f5b0f40ca5df1fb1d963881aba61/classes/class.post-type.wp-call-to-action.php#L40

I don't see the output anywhere in the footer of the CTA edit screen

Safe to assume we can remove?

**Comment by atwellpub** [comment]
I believe it powers this: 
http://screencast.com/t/1FUGqgOkDiqO
