### ISSUE TITLE
New Marketing Button / Shortcode setup done

### ISSUE THREAD

**Issue by DavidWells** [inboundnow/cta#125]
http://www.screencast.com/t/FBUHI9WArGJu

Can you give it a spin and see if you notice any quirks?

**Comment by atwellpub** [comment]
Looks like it's working great! It looks like it's using the same UI how did the refactor process go for you? What all did you have to do?

**Comment by DavidWells** [comment]
Rewrote all the JS with the button but used the same shortcode setup for the output

Killed thick box and used magnificent popup instead.

Oh also got rid of any direct tinyMCE references bc Wordpress changes that shit out from under us.

Should be easier to maintain and we shouldn't see as many issues with it (hopefully)
