### ISSUE TITLE
CTA php warning throwing on plugin deactivation

### ISSUE THREAD

**Issue by DavidWells** [inboundnow/cta#126]
Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /Users/davidwells/Dropbox/Sites/WP.dev/wp-content/plugins/cta/shared/classes/class.template-utils.php:2) in /Users/davidwells/Dropbox/Sites/WP.dev/wp-content/plugins/cta/classes/class.cta.variations.php on line 38

http://www.screencast.com/t/SgwU9fiZKeeo

**Comment by atwellpub** [comment]
There's a blank space before <?php
