### ISSUE TITLE
Error in send_conversion_admin_notification

### ISSUE THREAD

**Issue by kaoecoito** [inboundnow/cta#127]
In line 830 off class.form.php the headers is replaced and not concatenated.

           $headers = 'From: '. $from_name .' <'. $from_email .'>' . "\r\n";
           $headers = "Reply-To: ".$reply_to_email . "\r\n";

The correct use is

           $headers = 'From: '. $from_name .' <'. $from_email .'>' . "\r\n";
           $headers .= "Reply-To: ".$reply_to_email . "\r\n";

**Comment by atwellpub** [comment]
Thank you so much for discovering this and notifying us. Fix in place.
