### ISSUE TITLE
PHP warning from ACF class

### ISSUE THREAD

**Issue by DavidWells** [inboundnow/cta#130]
http://www.screencast.com/t/m6a6zWqa

Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'Inbound_Shared_ACF_BootStrap' does not have a method 'acf_register_global' in /Users/davidwells/Dropbox/Sites/WP.dev/wp-includes/plugin.php on line 503

**Comment by atwellpub** [comment]
Looks good. It might should be moved out into the ACF handler class for landing pages instead of set inside the ACF boostrap for shared, but for now it works well.
