### ISSUE TITLE
Problem with forms. Error in range field configuration causes notice print

### ISSUE THREAD

**Issue by daprela** [inboundnow/cta#133]
This message shows up if I enable debug:
`Notice: Undefined offset: 2 in D:\Bitnami\wampstack-5.4.32-0\apps\inboundfree\htdocs\wp-content\plugins\cta\shared\classes\class.form.php on line 419`

What happens is that while configuring the form in my Acacia template I forgot to add the step in the range field. I didn't get any error, so I didn't notice the problem. The third element in the $options array is missing as a result and the notice is printed.

However, there's another problem: I tried to edit the form again but I couldn't edit the range setup, so I had to delete the old field and add a new one. It doesn't seem very logic to me but maybe there's a reason for this that I don't know.

**Comment by atwellpub** [comment]
Latest commits should solve both issues. Let me know if there is any more trouble.
