### ISSUE TITLE
Inbound forms: css IDs not unique

### ISSUE THREAD

**Issue by daprela** [inboundnow/cta#134]
I don't know if this is the most appropriate place to post issues about forms, please let me know if I have to post them somewhere else.

The system gives an ID to each field in a form. However, there's a problem. In CSS, IDs are supposed to be unique. If I give the same name to two fields, they will end up having the same ID because the ID is named after the field name.
I suppose I'd have the same problem if I'd post the same form twice in a page (like, in the footer and in a sidebar), or two different forms but with a few fields having the same name

**Comment by atwellpub** [comment]
So the issue is if two forms have the same field name they will have the same class name and id name and that means they are unabled to be styled via external styling rules separately?

**Comment by daprela** [comment]
Actually, other forms plugins like contact form 7 don't use IDs at all. If you cannot guarantee that every ID is unique across all of your forms (and in my opinion it's hard to do it), it's better to avoid adding IDs at all, and work only with classes, just to avoid any confusion to the advanced user that wants to add his own styling.

**Comment by DavidWells** [comment]
IDs were added for faster lookup with jQuery/js ( they are faster than searching the dom for classes )

I don't think we can remove this without breaking alot of stuff ( custom CSS rules, custom JS actions, etc used by folks)

**Comment by DavidWells** [comment]
We can have the custom post type ID print out in classes field but we can't remove the non unique ID because of backwards compatibility.

The only fix to remove it is introducing a new form tool (which I'd like to do in the future)
