### ISSUE TITLE
Inbound forms: improving 'Show advanced options' link

### ISSUE THREAD

**Issue by daprela** [inboundnow/cta#135]
The 'advanced options' link inside each field editor of the inbound form in my opinion needs some improvements.
If I click on the options shown here
![improving show advanced options -1](https://cloud.githubusercontent.com/assets/6268698/10166102/bbeb4362-66ec-11e5-8ec7-8632bbafdf4e.png)

I find myself inside this
![improving show advanced options-2](https://cloud.githubusercontent.com/assets/6268698/10166137/e64a2ccc-66ec-11e5-93c2-b207362005ed.png)
which is a bit disorientating. The link shrinks, and an option shows up above it. For consistency, in my opinion the link should remain of the same size, or look like a button, and the 'exclude tracking' option moved below

**Comment by atwellpub** [comment]
If you would like to make improvements on this you are welcome to.

**Comment by daprela** [comment]
Ok, just give me some time to learn how the forms module works

**Comment by daprela** [comment]
Done, I think that the UI of that element now is better

**Comment by DavidWells** [comment]
This http://www.screencast.com/t/VDubGOhOVl looks too much like another
input field.

Can you make it look like a simple link with the wordpress blue with no
border?

Good job moving the exclude tracking =)

**Comment by daprela** [comment]
Done, check it out

**Comment by DavidWells** [comment]
way better. Remove underline on hoverstate though
http://www.screencast.com/t/Zw75UQbayOv

**Comment by atwellpub** [comment]
Removed underline, no need to worry about it @daprela
