### ISSUE TITLE
PHP errors after upgrade to PHP 7

### ISSUE THREAD

**Issue by tomcashman** [inboundnow/cta#142]
Hi,

I upgraded to PHP 7.0 on Ubuntu 14.04 and received the following error from the plugin.

Fatal error: Cannot use Sabberworm\CSS\Value\String as String because 'String' is a special class name in /var/www/cellusys.com/wp-content/plugins/cta/lib/Sabberworm/CSS/Parser.php on line 20

**Comment by daprela** [comment]
Hi @tomcashman 
thank you for reporting the problem. We will soon update the Sabberworm library with a version that supports PHP 7.

**Comment by atwellpub** [comment]
Saberworm updated to latest here:
https://github.com/sabberworm/PHP-CSS-Parser
