### ISSUE TITLE
Notice of undefined constant

### ISSUE THREAD

**Issue by daprela** [inboundnow/cta#144]
`Notice: Use of undefined constant WPL_PATH - assumed 'WPL_PATH' in D:\Bitnami\wampstack-5.4.32-0\apps\inboundfree\htdocs\wp-content\plugins\cta\calls-to-action.php on line 104`

It looks like `WPL_PATH` does not exists. I assume that `WP_CTA_PATH` should be the right one to use, and I'm going to fix it. I'll leave the issue open, if the constant to use is different please fix it, or close the issue.

**Comment by atwellpub** [comment]
confirmed thank you!
