### ISSUE TITLE
Issues with ACF5 loading in theme's functions.php

### ISSUE THREAD

**Issue by atwellpub** [inboundnow/cta#145]
*summary*

functions.php loads after plugins are loaded. We load shared in plugins_loaded hook. I cannot remember exactly why but when I tried to load shared any later I ran into issues in the past and plugins_loaded hook has worked the best for us over time. 

If a theme is using ACF5 and loading it in functions.php while running Landing Pages then LP's ACF4 is already loaded, causing possible conflicts. 

*see support issue:*
http://support.inboundnow.com/support/topic/acf-in-theme-conflicting-with-landing-pages/#post-117335

*possible solutions*

* Listen for constant when loading ACF that disables loading ACF4. User can define this constant in their wp-config.php
* Move loading shared away from plugins_loaded and into init, where user can define a similar constant into a init hook in their theme's functions.php file that will disable ACF loading.... this prevents the need to edit wp-config.php. But the draw back is we would have to thoroughly & manually test for bugs since we do not have an automated QA program developed yet.

**Comment by DavidWells** [comment]
What about having two shared loading points:

- keep the same plugins loaded one 
- add a new one that runs on init that loads things like acf

**Comment by atwellpub** [comment]
Ok good idea I moved the ACF Bootstrap to load in the after_theme_setup hook. ACF4 seems to load and work still.
