### ISSUE TITLE
Add older IE support with polyfill for CustomEvent

### ISSUE THREAD

**Issue by deltafactory** [inboundnow/cta#68]
While testing under IE8, some shared JS is causing errors. The current location for the relevant code is in https://github.com/inboundnow/cta/blob/master/shared/assets/frontend/js/inbound.js

The culprit is the CustomEvent object which wasn't supported in IE until version 10 or 11. Mozilla provides a polyfill snippet for IE 9 and 10 here, https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent#Polyfill.

I'm hoping to support back to IE8, not sure if that's something you're interested in.

**Comment by atwellpub** [comment]
Is this issue still open?

**Comment by deltafactory** [comment]
I haven't had time to work on it but will soon as long as the client supports IE8. What's the status of analytics version 2, since it would make sense to work on that code.

**Comment by atwellpub** [comment]
Analytics version two is out. David knows more on this issue than me though. I think it's been under his consideration for awhile.

**Comment by DavidWells** [comment]
I think ie8 works now. I added polyfill for custom events
