### ISSUE TITLE
Conversion Test (shortcode)

### ISSUE THREAD

**Issue by atwellpub** [inboundnow/cta#75]
[inbound-conversion] shortcode hasn't been developed yet but it will be soon. We'll want to make sure these conversions are tracked and contributed to a call to action.

**Comment by DavidWells** [comment]
Whats the idea here? Like conversion tracking from Google Adwords PPC?

**Comment by atwellpub** [comment]
Well say a user wanted to track a cta conversion by having a shortcode load on a thank you page rather than having a form submitted or a clicked link. Or maybe a signup via a 3rd party service. Having a shortcode like [inbound-conversion cta-id="123" landing-page-id="232"] or simple [inbound-conversion cta-id="1"] will let the user have a more 'concrete' conversion event. The same goes with providing the user a callback url that fires a conversion event. 

But the label on this is for creating a unit test that ensures this capability works.

**Comment by DavidWells** [comment]
I like the idea. Shortcodes are bad news though (bad bad bad bad bad user experience). 

A dead simple UI component in the page "Set conversion event on the page" would be clearer. With a box to say what the conversion is. 

Then we can add/remove additional form fields to that box instead of having a clunky shortcode with 5-6 params inside of it

**Comment by atwellpub** [comment]
Will you clarify this idea:

"Then we can add/remove additional form fields to that box instead of having a clunky shortcode with 5-6 params inside of it"

**Comment by DavidWells** [comment]
The UI would be action/filterable for people to add custom triggers, custom
JS, custom labels for Google analytics/segment.io etc.

If we use a shortcode it will be a mess

**Comment by atwellpub** [comment]
Refined idea:

### meta box just below advanced settings that has these settings:

* [ ] CHECBOX Disable automatic conversion tracking (disabled click tracking and form tracking for call to action / landing page )
* [ ] TEXTINPUT Enter in content ids to track as conversion event.
* [ ] READYONLY TEXTINPUT that shows callback URL for incrementing the landingpage/call to action.

**Comment by aikar** [comment]
@DavidWells I think most people using WordPress for professional needs will also be using Visual Composer.

You can integrate the shortcode into VC, giving a nice configuration interface for settings.

Here's documentation on that: https://wpbakery.atlassian.net/wiki/pages/viewpage.action?pageId=524332

Also to handle tracking which split it came from, simply set a cookie identifying the last creative accessed, then when the event fires, it credits to that one.

Ideally you should implement this as a pixel, like registering a custom (user defined) path like /conversion_event

That the shortcode then renders <img src="/conversion_event" width="1" height="1" />

Then if users get redirected to a thank you page outside of the WordPress platform, you can still fire the conversion pixel

**Comment by DavidWells** [comment]
@aikar We can't rely on third party plugins for anything

**Comment by aikar** [comment]
@DavidWells I don't mean to rely, I mean to support it if they also have it, which will improve use case of shortcodes.

If user doesn't use Visual Composer, they are likely already use to dealing with the technicalities of shortcodes anyways.

**Comment by atwellpub** [comment]
I plan to develop all three methods:

* shortcode
* mapping
* callback url (which can be used as a 1x1 pixel) 

They'll all be powered by the same API. 

We'll encourage direct mapping primarily via UI and the others secondarily as a alternative option.
