### ISSUE TITLE
[inbound-forms] Better customization of dropdown value/labels

### ISSUE THREAD

**Issue by atwellpub** [inboundnow/cta#80]
If this ticket is addressed it must be addressed for:
* Dropdowns
* Radios
* Checkboxes

Please use the following dropdown setup code locations as a guide to also discover the correct locations for Radios and Checkboxes as well.

Also make sure that the help text explains that the advanced method can be used OR comma separated labels can be used. 

- Where dropdowns are setup:
--https://github.com/inboundnow/cta/blob/7535e9354d6bca323d6dab8c31d072ea6fef8df4/shared/shortcodes/shortcodes/forms.php#L221-L227
- Where dropdowns are rendered:
-- https://github.com/inboundnow/cta/blob/master/shared/classes/class.form.php#L206

**Comment by burn0050** [comment]
I have created a merge request. Hope I did all that properly. This is my first time contributing open source code to github!
