### ISSUE TITLE
[ cta template ]  static template idea

### ISSUE THREAD

**Issue by atwellpub** [inboundnow/cta#82]
http://screencast.com/t/qxxnCLwcphUL
![image](https://cloud.githubusercontent.com/assets/2002207/5810046/8e07f2fa-a005-11e4-905d-02f81d0f3ace.png)

*  graphics presets included
* background color switching
* graphics preset color switching
* content 1
* button text
* button link 
* button background color
* button border color
* content 2

**Comment by MattBissett** [comment]
Howdy

**Comment by atwellpub** [comment]
groovy.

**Comment by atwellpub** [comment]
![tealium](https://cloud.githubusercontent.com/assets/2002207/15618378/58fe5dae-2413-11e6-9a55-18fbaf269973.png)

**Comment by atwellpub** [comment]
Ballin
