### ISSUE TITLE
Feature Request: CTAs per category

### ISSUE THREAD

**Issue by DavidWells** [inboundnow/cta#87]
"We would like to connect a Call to Action with a specific Wordpress category. We have severeal categories for ours post, and we would like to show a CTA related to each category. Can we do that? Thanks"

**Comment by atwellpub** [comment]
https://bitbucket.org/inboundnow/cta-global-placements/commits/3ac0d391803be1563aa0469b810b682b3ece223e

**Comment by atwellpub** [comment]
Now available. http://www.inboundnow.com/market/cta-global-placements/
