### ISSUE TITLE
Filter return if $post no set.

### ISSUE THREAD

**Issue by DavidWells** [inboundnow/cta#88]
From wordpress support: https://wordpress.org/support/topic/issue-with-motopress-ce-plugin?replies=3#post-6695616

Referencing this return: https://github.com/inboundnow/cta/blob/b368f6d8343aa2c83588f71ee7e330c06edd0919/classes/class.cta.render.php#L1085-L1087

Not sure what this does exactly and if we can remove the check or not

**Comment by atwellpub** [comment]
Fixed.
