### ISSUE TITLE
Warning: DOMDocument::loadHTML()

### ISSUE THREAD

**Issue by atwellpub** [inboundnow/cta#92]
Warning: DOMDocument::loadHTML(): Attribute href redefined in Entity, line: 11 in /Users/davidgregorywells/Dropbox/Sites/Local-Git/wp-content/plugins/_inbound-pro/core/cta/classes/class.cta.render.php on line 274

http://www.screencast.com/t/71CbILCc

**Comment by DavidWells** [comment]
http://www.screencast.com/t/b9TOwwRj

**Comment by DavidWells** [comment]
Warning: DOMDocument::loadHTML(): Attribute href redefined in Entity, line: 11 in /Users/davidgregorywells/Dropbox/Sites/Local-Git/wp-content/plugins/cta/classes/class.cta.render.php on line 274

Needs to get fixed for push

**Comment by atwellpub** [comment]
Pushed a fix, will you confirm fix? 

Unfortunately if there are repeared attribute elements in a html element it's going to throw the soft warning. The only thing I can think to do is mute errors and hope this doesn't shoot us in the foot on a troubleshooting issue one day in the future.

**Comment by DavidWells** [comment]
Fatal Parse error: syntax error, unexpected '$CTA_Load_Extensions' (T_VARIABLE) in /Users/davidgregorywells/Dropbox/Sites/Local-Git/wp-content/plugins/cta/classes/class.cta.render.php on line 52

**Comment by atwellpub** [comment]
What's the context of that one?

**Comment by DavidWells** [comment]
I pulled, and refreshed the page and the fatal is there from whatever you changed

**Comment by atwellpub** [comment]
k fixed.
