### ISSUE TITLE
Disable translations call to action

### ISSUE THREAD

**Issue by atwellpub** [inboundnow/cta#93]
@DavidWells 

We are getting more signups than we can address. Should we disable to call to action to save people from wasting time?

**Comment by atwellpub** [comment]
Hey David I suggest we get rid of of the offer for a free member ship, leave the call to action up for general request for help, and automatically accept all translators.  

If we get contacted by a power translator requesting to cash in on our original offer we will honor it. Otherwise we just let people join automatically and translate. 

What do you think?

**Comment by DavidWells** [comment]
Yeah sounds good to me. I accepted 1 per language but it seems like no one
is willing to actually do the work.

**Comment by atwellpub** [comment]
Not sure we can do automatic updates. But I have to cta updated and pushed to svn.

**Comment by atwellpub** [comment]
Also, we can't do it yet until Pro is ready, but I would like to setup an autoresponder that thanks people for signing up to be a translator that offers them a 15% off coupon. 

I'm about to send an email to our translators list using Inbound Pro from my local and let them know about the changes and appologies if they were denied and invite them to rejoin as a contributor.
