### ISSUE TITLE
Adding more HTML fields to inbound forms

### ISSUE THREAD

**Issue by atwellpub** [inboundnow/cta#94]
Adding these:

-url
-email
-tel
-datetime-local

**Comment by DavidWells** [comment]
This will break CSS on multiple templates

We don't need these

**Comment by atwellpub** [comment]
Commented out everything but 'slider'.

https://github.com/inboundnow/cta/commit/89e706033ae962c581ed37680e0f25c1d1950f7d

People will want them eventually though. We might want to task someone with putting them back and and making sure our templates work with html5 inputs.
