### ISSUE TITLE
Global CSS in options

### ISSUE THREAD

**Issue by DavidWells** [inboundnow/cta#96]
Where is the wp_cta_global_css options go from the CTA options panel?

Did we remove it a while ago?

We still have references to these in activation
```add_option( 'wp_cta_global_css', '', '', 'no' ); 
   add_option( 'wp_cta_global_js', '', '', 'no' );
```

**Comment by atwellpub** [comment]
We did. I looked over the entire code base and could not find where it was being implemented so I took it out of the Global Settings.

**Comment by DavidWells** [comment]
Ah cool. It was one of the security holes. A+
